type FilterToolbarProps = {
  search: string; sign: "all" | "positive" | "negative"; side: "all" | "LONG" | "SHORT"; minFunding: number; minEntrySpread: number; favoritesOnly: boolean; showingAll: boolean; total: number; onSearch: (value: string) => void; onSign: (value: "all" | "positive" | "negative") => void; onSide: (value: "all" | "LONG" | "SHORT") => void; onMinFunding: (value: number) => void; onMinEntrySpread: (value: number) => void; onFavoritesOnly: (value: boolean) => void; onShowingAll: (value: boolean) => void; onRefresh: () => void;
};

export function FilterToolbar(props: FilterToolbarProps) {
  return <section className="filter-toolbar panel" aria-label="Opportunity filters">
    <div className="filter-main"><label className="search-field"><span className="sr-only">Search symbols</span><span className="search-icon" aria-hidden="true">⌕</span><input value={props.search} onChange={(event) => props.onSearch(event.target.value)} placeholder="Search symbols" /></label><label><span>Funding sign</span><select value={props.sign} onChange={(event) => props.onSign(event.target.value as FilterToolbarProps["sign"])}><option value="all">All signs</option><option value="positive">Positive</option><option value="negative">Negative</option></select></label><label><span>BloFin side</span><select value={props.side} onChange={(event) => props.onSide(event.target.value as FilterToolbarProps["side"])}><option value="all">All sides</option><option value="LONG">Long</option><option value="SHORT">Short</option></select></label><label><span>Min |funding| %</span><input type="number" min="0" step="0.01" value={props.minFunding} onChange={(event) => props.onMinFunding(Number(event.target.value))} /></label><label><span>Min entry spread %</span><input type="number" step="0.01" value={props.minEntrySpread} onChange={(event) => props.onMinEntrySpread(Number(event.target.value))} /></label></div>
    <div className="filter-actions"><label className="toggle-label"><input type="checkbox" checked={props.favoritesOnly} onChange={(event) => props.onFavoritesOnly(event.target.checked)} /><span className="toggle" />Favorites only</label><div className="result-toggle"><button className={!props.showingAll ? "active" : ""} onClick={() => props.onShowingAll(false)}>Top 60</button><button className={props.showingAll ? "active" : ""} onClick={() => props.onShowingAll(true)}>Show all</button></div><button className="refresh-button" onClick={props.onRefresh}>↻ Refresh</button></div>
  </section>;
}
